name: 'Wood & Lace'
favicon: null
layout_spectrum: 0.49459
typography_spectrum: 0.50325
title: 'Wood & Lace'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4fcff'
    - '#201830'
    - '#c69f8c'
    - '#742d43'
    - '#565b68'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
