name: Truth Beauty and Goodness
favicon: null
layout_spectrum: 0.9344223032239825
typography_spectrum: 0.6683559261728078
title: 'Wood & Lace'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#092401'
    - '#ddffa1'
    - '#538d2f'
    - '#e473ff'
    - '#781a7a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
